package com.ivpulse.etl.staging;

public enum StagingEntity {
    CLIENT,
    ENGAGEMENT,
    ROLE,
    RATE_CARD,
    RESOURCE,
    ENGAGEMENT_RESOURCE,
    HIRING_STATUS,
    ONBOARDING_STATUS,
    BILLING_SNAPSHOT,
    TIMESHEET_SNAPSHOT,
    RESOURCE_HISTORY,
    LEAVE_TYPES,
    LEAVE_HISTORY,
    DESIGNATION,
    UNKNOWN
}
